all:
	gcc -c matrix.c -o matrix.o
	gcc hw0201.c matrix.o -o hw0201
	gcc hw0202.c -o hw0202
	gcc hw0203.c -o hw0203
	gcc -c ContributionCalculate.c -o ContributionCalculate.o
	gcc hw0205.c ContributionCalculate.o -o hw0205
	#gcc hw0204.c -o hw0204
clean:
	rm -rf matrix.o
	rm -rf hw0201
	rm -rf hw0202
	rm -rf hw0203
	rm -rf hw0204
	rm -rf ContributionCalculate.o
	rm -rf hw0205
	rm -rf hw0206
